version: "3"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: config/nginx/prod/Dockerfile
    volumes:
      - sharedvolume:/billshare/
  db:
    image: postgres
    env_file:
      - env/postgres.env
  app:
    restart: always
    env_file:
      - env/prod.env
    build:
      context: .
      dockerfile: config/app/prod/Dockerfile
    depends_on:
      - nginx
      - db
    volumes:
      - sharedvolume:/billshare/

volumes:
  sharedvolume: {}
