version: "3"

services:
  db:
    image: postgres
#  nginx:
#    image: nginx:latest
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/app
#      - ./config/nginx:/etc/nginx/conf.d
#    depends_on:
#      - app
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
