version: "3"

services:
  nginx:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: config/nginx/dev/Dockerfile
    stdin_open: true
    volumes:
      - sharedvolume:/billshare/
  db:
    image: postgres
    env_file:
      - env/postgres.env
  app:
    restart: always
    env_file:
      - env/dev.env
    build:
      context: .
      dockerfile: config/app/dev/Dockerfile
    stdin_open: true
    depends_on:
      - nginx
      - db
    volumes:
      - sharedvolume:/billshare/
      - .:/app

volumes:
  sharedvolume: {}
