# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
