# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20171108_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlineitem',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
