# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transactionlineitem_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='split_type',
            field=models.CharField(choices=[('percent', 'percent'), ('money', 'money')], default='money', max_length=255),
            preserve_default=False,
        ),
    ]
