# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('user', '0001_initial'), ('user', '0002_auto_20171017_0002')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.TextField(default='', max_length=255)),
                ('last_name', models.TextField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
