# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 22, 14, 9, 454502, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
