# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_second_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_last_login',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
