# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuser',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
