# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20171021_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
