# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20171107_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='updated_date',
            new_name='created_date',
        ),
    ]
